# Generated by Django 5.0.3 on 2024-03-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('adventure', 'Приключения'), ('romance', 'Роман'), ('fantasy', 'Фантастика'), ('detective', 'Детектив'), ('classical', 'Классика'), ('horror', 'Хоррор'), ('biography', 'Биография')], max_length=255),
        ),
    ]
